name: Prepare Release

on:
  workflow_dispatch:

jobs:
  call-reusable-release:
    uses: radiusred/.github/.github/workflows/reusable-release.yml@main
    with:
      approval_environment: release-approval
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
